FROM golang:1.20.7 AS debug

WORKDIR /app

RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz -C $(go env GOPATH)/bin
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD air

FROM golang:1.20.7 AS development
# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app
# Устанавливаем пакет golang-migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz -C $(go env GOPATH)/bin


FROM golang:1.20.7 AS build

WORKDIR /app

COPY . .

RUN go build -o ./tmp/main ./cmd/main.go

FROM golang:1.20.7 AS production

WORKDIR /app

# Устанавливаем пакет golang-migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz -C $(go env GOPATH)/bin

COPY --from=build /app/tmp/main ./main
COPY --from=build /app/.env ./.env
COPY --from=build /app/migrations ./migrations

CMD [ "./main" ]
